name: pr

on: [pull_request]

jobs:
  build:
    uses: wittdennis/pipelines/.github/workflows/container-image-build.yaml@1.13.11
    with:
      image-name: cloudnative-pg-postgres-18
      create-artifacts: false
